"use client";

import { useState, useEffect } from "react";
import { useAuth } from "@clerk/nextjs";
import {
	ShieldCheck,
	ExternalLink,
	Timer,
	Globe,
	Loader2,
	Copy,
	Trash2,
} from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

export default function DeliveriesPage() {
	const { getToken } = useAuth();
	const [deliveries, setDeliveries] = useState([]);
	const [isLoading, setIsLoading] = useState(true);

	useEffect(() => {
		async function fetchDeliveries() {
			try {
				const token = await getToken();
				const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/delivery`, {
					headers: { Authorization: `Bearer ${token}` },
				});
				const json = await res.json();
				setDeliveries(json.data || []);
			} catch (err) {
				console.error("Failed to fetch deliveries", err);
			} finally {
				setIsLoading(false);
			}
		}
		fetchDeliveries();
	}, [getToken]);

	const copyToClipboard = (token) => {
		const url = `${process.env.NEXT_PUBLIC_API_URL}/delivery/resolve/${token}`;
		navigator.clipboard.writeText(url);
		alert("Secure link copied to clipboard!");
	};

	const revokeDelivery = async (id) => {
		if (!confirm("Are you sure you want to revoke this delivery link?")) return;
		try {
			const token = await getToken();
			const res = await fetch(
				`${process.env.NEXT_PUBLIC_API_URL}/delivery/${id}/revoke`,
				{
					method: "PATCH",
					headers: { Authorization: `Bearer ${token}` },
				},
			);
			if (!res.ok) throw new Error("Failed to revoke delivery");
			setDeliveries((prev) => prev.filter((d) => d._id !== id));
		} catch (err) {
			alert(err.message);
		}
	};

	return (
		<div className="space-y-6 max-w-6xl mx-auto">
			<div>
				<h1 className="text-3xl font-bold tracking-tight">Deliveries</h1>
				<p className="text-muted-foreground mt-1">
					Active distribution links and access proxies.
				</p>
			</div>

			<Card className="border-border bg-card">
				<CardContent className="p-0">
					<table className="w-full text-sm">
						<thead>
							<tr className="border-b border-border bg-muted/30 text-muted-foreground uppercase text-[10px] tracking-wider">
								<th className="px-6 py-4 text-left font-medium">
									Target Asset
								</th>
								<th className="px-6 py-4 text-left font-medium">
									Generated By
								</th>
								<th className="px-6 py-4 text-left font-medium">Expires</th>
								<th className="px-6 py-4 text-right font-medium">Actions</th>
							</tr>
						</thead>
						<tbody className="divide-y divide-border">
							{isLoading ? (
								<tr>
									<td colSpan="4" className="py-20 text-center">
										<Loader2 className="animate-spin inline mr-2" /> Loading
										active links...
									</td>
								</tr>
							) : deliveries.length === 0 ? (
								<tr>
									<td colSpan="4" className="py-20 text-center">
										<Globe className="w-10 h-10 text-muted-foreground/30 mx-auto mb-3" />
										<p className="text-muted-foreground">
											No active distribution links found.
										</p>
									</td>
								</tr>
							) : (
								deliveries.map((delivery) => (
									<tr
										key={delivery._id}
										className="hover:bg-muted/30 transition-colors"
									>
										<td className="px-6 py-4 font-medium flex items-center gap-2">
											<ShieldCheck className="w-4 h-4 text-blue-500" />
											{/* Accessing the populated title */}
											{delivery.familyId?.title || "Unknown Asset"}
										</td>
										<td className="px-6 py-4 text-muted-foreground">
											{delivery.createdBy}
										</td>
										<td className="px-6 py-4">
											<Badge
												variant="outline"
												className="bg-amber-500/10 text-amber-500 gap-1"
											>
												<Timer className="w-3 h-3" />
												{new Date(delivery.expiresAt).toLocaleString()}
											</Badge>
										</td>
										<td className="px-6 py-4 text-right">
											<Button
												variant="ghost"
												size="sm"
												onClick={() => copyToClipboard(delivery.token)}
											>
												<Copy className="w-4 h-4 mr-2" /> Copy Link
											</Button>
											<Button
												variant="ghost"
												size="sm"
												className="text-destructive hover:text-destructive"
												onClick={() => revokeDelivery(delivery._id)}
											>
												<Trash2 className="w-4 h-4" />
											</Button>
										</td>
									</tr>
								))
							)}
						</tbody>
					</table>
				</CardContent>
			</Card>
		</div>
	);
}
