
services:
  mongodb:
    image: mongo:6.0
    container_name: kevlar-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data:/data/db
    networks:
      - kevlar-network

  redis:
    image: redis:7-alpine
    container_name: kevlar-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - kevlar-network

  minio:
    image: minio/minio:latest
    container_name: kevlar-minio
    restart: unless-stopped
    # ports:
      # - "9000:9000" 
      # - "9001:9001" 
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpassword
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - kevlar-network

  minio-setup:
    image: minio/mc:latest
    container_name: kevlar-minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5
      /usr/bin/mc alias set myminio http://minio:9000 admin adminpassword;
      /usr/bin/mc mb myminio/kevlar-storage --ignore-existing;
      /usr/bin/mc anonymous set download myminio/kevlar-storage;
      /usr/bin/mc anonymous set public myminio/kevlar-storage; 
      exit 0;
      "
    networks:
      - kevlar-network

  backend:
    build:
      context: ./kevlar-core 
      dockerfile: Dockerfile
    image: kevlar-backend-image:latest
    container_name: kevlar-backend
    restart: unless-stopped
    # ports:
      # - "3000:3000"
    environment:
      # - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/kevlar?authSource=admin
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_PORT=${MINIO_PORT}
      - MINIO_EXTERNAL_ENDPOINT=${MINIO_EXTERNAL_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-admin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-adminpassword}
      - MINIO_DEFAULT_BUCKET=${MINIO_DEFAULT_BUCKET}
      - MINIO_USE_SSL=${MINIO_USE_SSL}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - DRM_SECRET_KEY=${DRM_SECRET_KEY}
      - BACKEND_HOST=${BACKEND_HOST}
    depends_on:
      - mongodb
      - redis
      - minio
    networks:
      - kevlar-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: kevlar-nginx:latest
    depends_on:
      - backend
      - minio
    ports:
      - "9000:9000"
      - "3000:3000"
    networks:
      - kevlar-network

  # frontend:
  #   build:
  #     context: ./kevlar-web 
  #     dockerfile: Dockerfile
  #   image: kevlar-frontend-image:latest
  #   container_name: kevlar_frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3001:3001" 
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:3000/api/v1
  #     - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
  #     - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
  #     - NEXT_PUBLIC_CLERK_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_SIGN_IN_URL}
  #     - NEXT_PUBLIC_CLERK_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_SIGN_UP_URL}
  #     - NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL}
  #     - NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=${NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL}
  #   depends_on:
  #     - backend
  #   networks:
  #     - kevlar-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  kevlar-network:
    driver: bridge
