apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: kevlar-nginx:latest
          name: nginx
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
