apiVersion: v1
kind: Secret
metadata:
  name: kevlar-secrets
type: Opaque
stringData:
  clerk-publishable-key: ""
  clerk-secret-key: ""
  drm-secret-key: ""
  minio-access-key: ""
  minio-secret-key: ""
  mongo-uri: ""
